CREATE SCHEMA IF NOT EXISTS schopping_list DEFAULT CHARACTER SET utf8;
USE schopping_list;

CREATE TABLE IF NOT EXISTS Product (
  id BIGINT NOT NULL AUTO_INCREMENT,
  name VARCHAR (100)  NOT NULL,
  price DECIMAL (10,3) NOT NULL,
  category VARCHAR (100) NULL,
  discount DECIMAL (10.3) NULL,
  description VARCHAR (100) NULL ,
  user_id BIGINT NULL,
  created TIMESTAMP DEFAULT CURRENT_TIMESTAMP ,
  PRIMARY KEY (id)
  )

  ENGINE = InnoDB
  AUTO_INCREMENT = 1002;

   CREATE TABLE IF NOT EXISTS users (
    id BIGINT NOT NULL AUTO_INCREMENT,
    login VARCHAR(100) NOT NULL,
    password VARCHAR(100) NOT NULL,
    created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
)
    ENGINE = InnoDB
    AUTO_INCREMENT = 1002;

ALTER TABLE schopping_list ADD CONSTRAINT user_products_fk FOREIGN KEY (user_id) REFERENCES users(id)
